"""
Robot Framework Resource File Exporter.

Exports selected UI elements to Robot Framework resource files
with variables and keywords for test automation.
"""

from typing import List, Dict, Any, Optional, TYPE_CHECKING
from pathlib import Path
from datetime import datetime
import re

from ..core.tree import DOMTree, DOMElement, ElementType

if TYPE_CHECKING:
    from ..core.element_definition import ElementDefinition


class RobotResourceExporter:
    """
    Exports DOM elements to Robot Framework resource files.

    Generates:
    - Variables for element locators
    - Keywords for common actions (click, input, verify)
    - Documentation with element metadata
    """

    # Template for the resource file
    RESOURCE_TEMPLATE = '''*** Comments ***
# ==============================================================================
# {title}
# ==============================================================================
# Auto-generated by Visual DOM Viewer
# Generated: {timestamp}
# Source: {source}
# Platform: {platform}
# Screen: {screen_width}x{screen_height}
# ==============================================================================

*** Settings ***
Documentation    {documentation}
Library          VisualLibrary

*** Variables ***
{variables}

*** Keywords ***
{keywords}
'''

    def __init__(self):
        self._naming_strategy = 'text_first'  # 'text_first', 'type_first', 'id_only'
        self._include_coordinates = True
        self._include_comments = True
        self._generate_keywords = True

    def set_naming_strategy(self, strategy: str) -> None:
        """Set variable naming strategy."""
        if strategy in ['text_first', 'type_first', 'id_only']:
            self._naming_strategy = strategy

    def export(
        self,
        elements: List[DOMElement],
        output_path: str,
        dom_tree: Optional[DOMTree] = None,
        title: str = "UI Elements",
        documentation: str = ""
    ) -> bool:
        """
        Export elements to Robot Framework resource file.

        Args:
            elements: List of elements to export
            output_path: Output file path (.resource or .robot)
            dom_tree: Optional DOM tree for metadata
            title: Title for the resource file
            documentation: Documentation string

        Returns:
            True if export successful
        """
        try:
            # Generate variables section
            variables = self._generate_variables(elements)

            # Generate keywords section
            keywords = self._generate_keywords(elements) if self._generate_keywords else ""

            # Get metadata
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            source = dom_tree.metadata.get('source_file', 'Unknown') if dom_tree else 'Unknown'
            platform = dom_tree.source if dom_tree else 'unknown'
            screen_width = dom_tree.screen_width if dom_tree else 0
            screen_height = dom_tree.screen_height if dom_tree else 0

            if not documentation:
                documentation = f"Resource file for {title} with {len(elements)} elements"

            # Format the template
            content = self.RESOURCE_TEMPLATE.format(
                title=title,
                timestamp=timestamp,
                source=source,
                platform=platform,
                screen_width=screen_width,
                screen_height=screen_height,
                documentation=documentation,
                variables=variables,
                keywords=keywords
            )

            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)

            return True

        except Exception as e:
            print(f"Error exporting to Robot: {e}")
            return False

    def _generate_variables(self, elements: List[DOMElement]) -> str:
        """Generate variables section."""
        lines = []
        used_names = set()

        for elem in elements:
            var_name = self._generate_unique_name(elem, used_names)
            used_names.add(var_name)

            locator = self._generate_locator(elem)

            if self._include_comments:
                comment = self._generate_variable_comment(elem)
                lines.append(comment)

            lines.append(f"${{{var_name}}}    {locator}")
            lines.append("")

        return '\n'.join(lines)

    def _generate_keywords(self, elements: List[DOMElement]) -> str:
        """Generate keywords section."""
        lines = []
        used_names = set()

        for elem in elements:
            var_name = self._generate_unique_name(elem, set())  # Fresh set for consistency
            keyword_name = self._generate_keyword_name(elem, used_names)
            used_names.add(keyword_name)

            keyword_lines = self._generate_keyword_for_element(elem, var_name, keyword_name)
            lines.extend(keyword_lines)
            lines.append("")

        return '\n'.join(lines)

    def _generate_unique_name(self, elem: DOMElement, used_names: set) -> str:
        """Generate unique variable name for element."""
        base_name = self._generate_base_name(elem)

        # Clean the name
        clean_name = self._clean_name(base_name)

        # Ensure uniqueness
        final_name = clean_name
        counter = 1
        while final_name in used_names:
            final_name = f"{clean_name}_{counter}"
            counter += 1

        return final_name

    def _generate_base_name(self, elem: DOMElement) -> str:
        """Generate base name based on naming strategy."""
        type_name = elem.type.value.upper()
        text_name = elem.text[:30] if elem.text else ""

        if self._naming_strategy == 'text_first':
            if text_name:
                return f"{type_name}_{text_name}"
            return f"{type_name}_{elem.id}"

        elif self._naming_strategy == 'type_first':
            return f"{type_name}_{elem.id}"

        else:  # id_only
            return elem.id.upper()

    def _clean_name(self, name: str) -> str:
        """Clean name for use as Robot Framework variable."""
        # Replace non-alphanumeric with underscore
        clean = re.sub(r'[^a-zA-Z0-9]', '_', name)
        # Remove consecutive underscores
        clean = re.sub(r'_+', '_', clean)
        # Remove leading/trailing underscores
        clean = clean.strip('_')
        # Ensure it starts with a letter
        if clean and not clean[0].isalpha():
            clean = 'E_' + clean
        return clean.upper() or 'ELEMENT'

    def _generate_locator(self, elem: DOMElement) -> str:
        """Generate locator string for element."""
        parts = []

        # Primary locator: text or type
        if elem.text:
            # Escape special characters
            escaped_text = elem.text.replace('\\', '\\\\').replace('"', '\\"')
            parts.append(f'text="{escaped_text}"')

        parts.append(f'type={elem.type.value}')

        # Add coordinates if enabled
        if self._include_coordinates and elem.bbox:
            parts.append(f'bbox=[{elem.bbox.x},{elem.bbox.y},{elem.bbox.width},{elem.bbox.height}]')

        # Add ID
        parts.append(f'id={elem.id}')

        return '    '.join(parts)

    def _generate_variable_comment(self, elem: DOMElement) -> str:
        """Generate comment for variable."""
        parts = [f"# Element: {elem.type.value}"]

        if elem.text:
            text_preview = elem.text[:50] + "..." if len(elem.text) > 50 else elem.text
            parts.append(f'Text: "{text_preview}"')

        if elem.bbox:
            parts.append(f"Position: ({elem.bbox.x}, {elem.bbox.y})")
            parts.append(f"Size: {elem.bbox.width}x{elem.bbox.height}")

        if elem.confidence < 1.0:
            parts.append(f"Confidence: {elem.confidence:.2f}")

        return ' | '.join(parts)

    def _generate_keyword_name(self, elem: DOMElement, used_names: set) -> str:
        """Generate keyword name for element."""
        # Create readable keyword name
        if elem.text:
            base = elem.text[:30]
        else:
            base = elem.type.value

        # Title case with spaces
        words = re.sub(r'[^a-zA-Z0-9]', ' ', base).split()
        name = ' '.join(word.capitalize() for word in words if word)

        # Add action prefix based on type
        if elem.type == ElementType.BUTTON:
            name = f"Click {name}"
        elif elem.type == ElementType.INPUT_FIELD:
            name = f"Enter {name}"
        elif elem.type == ElementType.CHECKBOX:
            name = f"Toggle {name}"
        elif elem.type == ElementType.DROPDOWN:
            name = f"Select From {name}"
        else:
            name = f"Interact With {name}"

        # Ensure uniqueness
        final_name = name
        counter = 1
        while final_name in used_names:
            final_name = f"{name} {counter}"
            counter += 1

        return final_name

    def _generate_keyword_for_element(
        self,
        elem: DOMElement,
        var_name: str,
        keyword_name: str
    ) -> List[str]:
        """Generate keyword definition for element."""
        lines = []

        if elem.type == ElementType.BUTTON:
            lines.extend([
                keyword_name,
                f"    [Documentation]    Click the {elem.text or elem.type.value} button",
                f"    Click Element    ${{{var_name}}}",
            ])

        elif elem.type == ElementType.INPUT_FIELD:
            lines.extend([
                keyword_name,
                f"    [Documentation]    Enter text in {elem.text or 'input field'}",
                "    [Arguments]    ${text}",
                f"    Input Text    ${{{var_name}}}    ${{text}}",
            ])

        elif elem.type == ElementType.CHECKBOX:
            lines.extend([
                keyword_name,
                f"    [Documentation]    Toggle {elem.text or 'checkbox'}",
                f"    Click Element    ${{{var_name}}}",
            ])

        elif elem.type == ElementType.DROPDOWN:
            lines.extend([
                keyword_name,
                f"    [Documentation]    Select option from {elem.text or 'dropdown'}",
                "    [Arguments]    ${option}",
                f"    Click Element    ${{{var_name}}}",
                f"    Click Element    text=${{option}}",
            ])

        elif elem.type == ElementType.TEXT or elem.type == ElementType.LABEL:
            lines.extend([
                f"Verify {keyword_name.replace('Interact With ', '')} Is Visible",
                f"    [Documentation]    Verify {elem.text or 'text'} is visible",
                f"    Element Should Be Visible    ${{{var_name}}}",
            ])

        else:
            lines.extend([
                keyword_name,
                f"    [Documentation]    Interact with {elem.text or elem.type.value}",
                f"    Click Element    ${{{var_name}}}",
            ])

        return lines

    def export_selected_only(
        self,
        dom_tree: DOMTree,
        output_path: str,
        **kwargs
    ) -> bool:
        """
        Export only selected elements from DOM tree.

        Args:
            dom_tree: DOM tree with selected elements
            output_path: Output file path

        Returns:
            True if export successful
        """
        selected = [
            elem for elem in dom_tree.get_all_elements()
            if elem.selected
        ]

        if not selected:
            print("No elements selected for export")
            return False

        return self.export(selected, output_path, dom_tree, **kwargs)

    def preview(self, elements: List[DOMElement]) -> str:
        """
        Generate preview of export without writing to file.

        Args:
            elements: List of elements

        Returns:
            Preview string
        """
        variables = self._generate_variables(elements)
        keywords = self._generate_keywords(elements) if self._generate_keywords else ""

        return f"*** Variables ***\n{variables}\n\n*** Keywords ***\n{keywords}"

    def export_definitions(
        self,
        definitions: List['ElementDefinition'],
        output_path: str,
        dom_tree: Optional[DOMTree] = None,
        title: str = "User Defined Elements",
        documentation: str = ""
    ) -> bool:
        """
        Export user-defined elements with custom names and selected properties.

        Args:
            definitions: List of ElementDefinition objects
            output_path: Output file path
            dom_tree: Optional DOM tree for metadata
            title: Title for the resource file
            documentation: Documentation string

        Returns:
            True if export successful
        """
        try:
            # Generate variables section from definitions
            variables = self._generate_definition_variables(definitions)

            # Generate keywords section from definitions
            keywords = self._generate_definition_keywords(definitions) if self._generate_keywords else ""

            # Get metadata
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            source = dom_tree.metadata.get('source_file', 'Unknown') if dom_tree else 'Unknown'
            platform = dom_tree.source if dom_tree else 'unknown'
            screen_width = dom_tree.screen_width if dom_tree else 0
            screen_height = dom_tree.screen_height if dom_tree else 0

            if not documentation:
                documentation = f"Resource file for {title} with {len(definitions)} user-defined elements"

            # Format the template
            content = self.RESOURCE_TEMPLATE.format(
                title=title,
                timestamp=timestamp,
                source=source,
                platform=platform,
                screen_width=screen_width,
                screen_height=screen_height,
                documentation=documentation,
                variables=variables,
                keywords=keywords
            )

            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)

            return True

        except Exception as e:
            print(f"Error exporting definitions to Robot: {e}")
            return False

    def _generate_definition_variables(self, definitions: List['ElementDefinition']) -> str:
        """Generate variables section from user definitions."""
        lines = []

        for defn in definitions:
            # Use user-defined name
            var_name = self._clean_name(defn.name)

            # Generate locator from selected properties only
            locator = self._generate_definition_locator(defn)

            if self._include_comments:
                comment = self._generate_definition_comment(defn)
                lines.append(comment)

            lines.append(f"${{{var_name}}}    {locator}")
            lines.append("")

        return '\n'.join(lines)

    def _generate_definition_locator(self, defn: 'ElementDefinition') -> str:
        """Generate locator string from user-selected properties."""
        parts = []

        # Only include properties that user selected
        for prop in defn.selected_properties:
            value = defn.property_values.get(prop)
            if value is None:
                continue

            if prop == 'text':
                escaped_text = str(value).replace('\\', '\\\\').replace('"', '\\"')
                parts.append(f'text="{escaped_text}"')
            elif prop == 'type':
                parts.append(f'type={value}')
            elif prop == 'bbox':
                if isinstance(value, list):
                    parts.append(f'bbox=[{",".join(map(str, value))}]')
                else:
                    parts.append(f'bbox={value}')
            elif prop == 'center':
                if isinstance(value, (list, tuple)):
                    parts.append(f'center=[{value[0]},{value[1]}]')
                else:
                    parts.append(f'center={value}')
            elif prop in ('x', 'y', 'width', 'height', 'confidence'):
                parts.append(f'{prop}={value}')
            elif prop == 'id':
                parts.append(f'id={value}')
            else:
                # Custom properties
                parts.append(f'{prop}="{value}"')

        return '    '.join(parts) if parts else 'id=' + defn.element_id

    def _generate_definition_comment(self, defn: 'ElementDefinition') -> str:
        """Generate comment for a definition."""
        parts = [f"# {defn.name}"]

        if defn.description:
            parts.append(f"({defn.description})")

        props = ', '.join(defn.selected_properties)
        parts.append(f"| Defined by: {props}")

        return ' '.join(parts)

    def _generate_definition_keywords(self, definitions: List['ElementDefinition']) -> str:
        """Generate keywords section from user definitions."""
        lines = []

        for defn in definitions:
            var_name = self._clean_name(defn.name)
            elem_type = defn.property_values.get('type', 'unknown')
            text = defn.property_values.get('text', '')

            keyword_lines = self._generate_definition_keyword(defn, var_name, elem_type, text)
            lines.extend(keyword_lines)
            lines.append("")

        return '\n'.join(lines)

    def _generate_definition_keyword(
        self,
        defn: 'ElementDefinition',
        var_name: str,
        elem_type: str,
        text: str
    ) -> List[str]:
        """Generate keyword definition for a user-defined element."""
        lines = []

        # Create readable keyword name from user's element name
        keyword_name = defn.name.replace('_', ' ').title()

        # Determine action based on type
        if elem_type == 'button':
            lines.extend([
                f"Click {keyword_name}",
                f"    [Documentation]    Click the {text or defn.name} button",
                f"    Click Element    ${{{var_name}}}",
            ])

        elif elem_type in ('input', 'input_field', 'text_field'):
            lines.extend([
                f"Enter Text In {keyword_name}",
                f"    [Documentation]    Enter text in {text or defn.name}",
                "    [Arguments]    ${text}",
                f"    Input Text    ${{{var_name}}}    ${{text}}",
            ])

        elif elem_type == 'checkbox':
            lines.extend([
                f"Toggle {keyword_name}",
                f"    [Documentation]    Toggle {text or defn.name}",
                f"    Click Element    ${{{var_name}}}",
            ])

        elif elem_type in ('dropdown', 'select', 'combobox'):
            lines.extend([
                f"Select From {keyword_name}",
                f"    [Documentation]    Select option from {text or defn.name}",
                "    [Arguments]    ${option}",
                f"    Click Element    ${{{var_name}}}",
                f"    Click Element    text=${{option}}",
            ])

        elif elem_type in ('text', 'label'):
            lines.extend([
                f"Verify {keyword_name} Is Visible",
                f"    [Documentation]    Verify {text or defn.name} is visible",
                f"    Element Should Be Visible    ${{{var_name}}}",
            ])

        else:
            lines.extend([
                f"Click {keyword_name}",
                f"    [Documentation]    Click {text or defn.name}",
                f"    Click Element    ${{{var_name}}}",
            ])

        return lines
